### ISSUE TITLE
Alpha Playtest: Less blank space in dialogue boxes

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#13]
A playtester said we could add more space below the speaker name, and maybe even make the name of the speaker larger, so there is less blank space to the bottom of the box.

But there is also the concern of what if the dialogue is very long? Could centrally align (vertically) the body text?

**Comment by Cloud7050** [comment]
Ok either way

**Comment by rui-han-crh** [comment]
Completed
