### ISSUE TITLE
Alpha playtest: Reset/undo not working

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#2]
Some levels cannot R to reset and Z to undo.

Something to do with dialogue system alongside another thing releasing input capture early? (Need to count how many systems are disabling then releasing input)
Or some levels not having it pasted in?

**Comment by Cloud7050** [comment]
There is some data size error when pressing undo on the last crimson level of the alpha

**Comment by rui-han-crh** [comment]
> Something to do with dialogue system alongside another thing releasing input capture early? (Need to count how many systems are disabling then releasing input)

Separate issue, fixed.
