### ISSUE TITLE
Refine anchor/rope graphic

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#31]
Selector sphere mesh has been hidden, but there appeared to be some issues with the anchor/rope alignment and stuff as of yesterday. Can close if already fixed.

See also #15

**Comment by Cloud7050** [comment]
During the alpha, the anchor had a white box that would stay on the map while the rope went up. Unsure if still relevant

**Comment by rui-han-crh** [comment]
The anchor staying was intended. Oswald unties the rope around the anchor and ties it onto himself to get pulled back up

**Comment by Cloud7050** [comment]
I see, if the rope already looks correct then can close ig

**Comment by rui-han-crh** [comment]
Fixed via enhancement to #7
