### ISSUE TITLE
Error when pressing space in level with no fishnet

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#39]
When pressing space too fast/at a weird time before/during dialogue cutscene, errors are generated to do with not having fishnets on that particular level. Did not manage to get the specific error message. But otherwise if we don't encounter this, then pressing space during gameplay just does nothing as expected.

May be related, but a similar issue sometimes happens where movement keys get locked out, but other keys like shift+escape for options menu still works.

Also unable to consistently reproduce.

**Comment by rui-han-crh** [comment]
I'm not sure what this is referring to, does anyone have a reference to this? I've never seen an error with not having fishnets.

**Comment by Cloud7050** [comment]
I'll add more info if I can replicate it

**Comment by Cloud7050** [comment]
Will reopen if it occurs again
