### ISSUE TITLE
Error message upon restart

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#44]
An error appears at the top left when restarting the first donut level in serene

**Comment by Cloud7050** [comment]
"The data size is incorrect"
Still happens in other levels too

**Comment by rui-han-crh** [comment]
The error suddenly stopped happening and I don't know why. This happening once before the error came back again, but now it looks like its gone.

**Comment by Cloud7050** [comment]
Can reopen if it comes back
